### ISSUE TITLE
Aruba Instant Component Doesn't Update Entities

### ISSUE THREAD

**Issue by mww012** [mww012/home-assistant#3]
Aruba Instant component doesn't update entities after first creation.

**Comment by apaperclip** [comment]
Looks like a good start! For what its worth, I think the unifi component adds an entity for each client and maintains them.

**Comment by mww012** [comment]
That's my end goal.  As soon as I can reliably get entities updated in HA I want to build a more complex config flow so that you can pick and choose which clients to track.  Didn't want to bite off more than I can chew in this first attempt.

**Comment by apaperclip** [comment]
I'm not sure if there are other ways but I just disabled the discovered entities (clients).  This feels like the same as setting track: false in the legacy known_devices.yaml.  And I bet the  toggle  'enable newly added entities" behaves the same as the legacy configuration.yaml setting track_new_devices that did the same.

I only mentioned unifi as a potential example of a similar component that keeps clients updated for  ideas.


Have you had any thoughts on associating the clients or other attributes with device objects in ha? I dont know if ha supports the dynamic nature of clients to an ap though.

**Comment by mww012** [comment]
Pushed an update to the dev branch that should fix the entity update issue.  @apaperclip give it a shot when you have a chance. #

**Comment by apaperclip** [comment]
Testing so far so good! Nice work! 
Some general questions so I can make sure what I'm seeing is expected.

With the legacy component the default poll interval was 12s and adjustable if needed, and the consider_home could be defined. Can those be adjusted in the new method?

also - how are you testing - what ha install, etc?

To quickly test I just patched the commits into a beta version docker container, but going forward this is probably not the easiest or quickest.  I'd like to use the vscode +devcontainer approach but from what I can tell vscode and docker need to be on the same host, but I dont have that right now and wasn't planning on doing that to an existing host. Maybe I'll spin up a linux vm just for that.

**Comment by mww012** [comment]
The poll interval should be doable.  I'm not sure about the consider_home piece.  I can look into it though.

I'm testing with vscode+devcontainer on a Mac.  So far that's been the simplest option I've found.  I only have it up and running while I'm working on the component.  After that I make sure the container is shut down.  I can definitely recommend this route.  It actually looks like you can attach to a docker container on a remote host.  I haven't tried it but it looks like a supported way of doing things.  Look [here](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host).  I haven't tried it but it should work.

**Comment by apaperclip** [comment]
Testing still going well. I spun up a dev vm so I can clone off your repo into a running environment.

Not sure the best place to discuss general things, Feel free to point me elsewhere. I can create separate issues for these and other questions if that would be better.

- When the legacy device tracker has the device at home it displays the lat/lon of the HA configured location as entity attribute

```
source_type: router
latitude: 37.96152331396614
longitude: -115.81787109375001
gps_accuracy: 0
scanner: ArubaDeviceScanner
friendly_name: tracker1
```


- When using legacy, if the device goes away  these attributes are no longer available. This may be useful if someone is using the attributes and continuting to populate them when a device is not connnected could cause confusion. 

legacy when associated:
```
source_type: router
latitude: 37.96152331396614
longitude: -115.81787109375001
gps_accuracy: 0
scanner: ArubaDeviceScanner
friendly_name: tracker1
```

legacy when disconnected
```
source_type: router
scanner: ArubaDeviceScanner
friendly_name: tracker1
```
- I noticed when a device is not associated w/ the APs during HA restart, it will not be detected in the integration. Is on-HA-restart the only time clients are detected and created as entities?  I think it would be ideal if anytime a client associated it would be detected by the integration. Whether or not it is enabled would depend on the 'track new' setting

**Comment by mww012** [comment]
As of right now, the only time devices are added is during startup.  I agree that adding entities should happen when new wireless clients are discovered.  That's on my to-do list.  Here's my thoughts on a roadmap of sorts.  What do you think?

**Short term roadmap**
- Add an Aruba logo.
- Allow user to select polling interval with min polling interval enforced to 10 seconds (can make that less if needed).
- Config flow to allow user to select specific devices to track if desired.  May potentially have an "all" option.
- If tracking "all" clients, add entity when a new client is discovered.  Restart of HA should not be required.
- Update AP status as well as clients.  Right now, APs are discovered on boot but their state isn't polled again.
- Set entity attributes to None/""/null when client is considered Away.
- Add lat/lon attributes to entities.

**Long term roadmap**
- Incorporate ssh based component and allow user to select SSH or API methodology.
- Autodiscover Instant version and suggest SSH or API method to user.

**Comment by apaperclip** [comment]
> The poll interval should be doable. I'm not sure about the consider_home piece. I can look into it though.

Not sure how critical poll interval is compared to other items, I just noticed it was a difference between the new and legacy versions.  Consider home may be more important to others.  I'll have to dig around the other non-legacy device trackers and see if any offer it.


> I'm testing with vscode+devcontainer on a Mac. So far that's been the simplest option I've found. I only have it up and running while I'm working on the component. After that I make sure the container is shut down. I can definitely recommend this route. It actually looks like you can attach to a docker container on a remote host. I haven't tried it but it looks like a supported way of doing things. Look [here](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host). I haven't tried it but it should work.

I spent a few hours one night trying to get the vsdocde+devcontainer to work where vscode was on my desktop and the docker host was a remote linux host. I could never get the prompt to "reopen in container" or find the command pallet option to do it.  Everything else w/ remote container support worked, just not that.  I think there may be a way with setting up keys and such but I didnt want to spend the time and run into another item to track down.  The linux vm I built worked just like the ha page said so I cloned your repo and spun up the container, it seems more straight forward with code and docker are on the same host.

**Comment by apaperclip** [comment]
Awesome list.


> As of right now, the only time devices are added is during startup. I agree that adding entities should happen when new wireless clients are discovered. That's on my to-do list. Here's my thoughts on a roadmap of sorts. What do you think?
> 
> **Short term roadmap**
> 
> * Add an Aruba logo.
> * Allow user to select polling interval with min polling interval enforced to 10 seconds (can make that less if needed).
>> I'm sure 10 is more than quick enough.  I never adjusted the 12s of the legacy integration
> * Config flow to allow user to select specific clients to track if desired.  May potentially have an "all" option.
> * If tracking "all" clients, add entity when a new client is discovered.  Restart of HA should not be required.
>>If not all, would new clients still be added but in a disabled state? This would be how I would use it, I don't track all, but i want any client that joins to be discovered somewhere so I can enable tracking for it. 
> * Update AP status as well as clients.  Right now, APs are discovered on boot but their state isn't polled again.
>>This gave me an idea, but when I went to look I just realized devices don't show up as entities.  It would be cool to add info for the devices(aps) but I'm not sure how it would be accessed. Tracking # of clients, channel, radios, power, noise, % utilized, which is active for the virtual ip, etc.  There are a ton of stats, not sure which ones make the most sense to add withough recreating a whole monitoring system.
> * Set entity attributes to None/""/null when client is considered Away.
>> What is best practice, nulling out, or removing the attribute?  Thinking downstream impacts if someone pulls an attribute out in a template, sensor, or card.
> * Add lat/lon attributes to entities.
> 
> **Long term roadmap**
> 
> * Incorporate ssh based component and allow user to select SSH or API methodology.
> * Autodiscover Instant version and suggest SSH or API method to user.
>> I like this idea.

**Comment by mww012** [comment]
Nice!  Glad you got a good dev/test setup going.

- The polling interval was actually really easy to add.  I've got it working but need to figure out how to enforce the minimum.  Shouldn't be hard.
- My goal for tracking specific clients would be to use an options flow.  It would be automatically invoked after you first submit the info to add the component.  As soon as you click "submit" we'll validate that your info is good, from there you'll get a form with a list of all discovered clients.  You check the ones you want to track and we'll create entities for those.  After that first setup, you can click the "options" button on the integration for the component.  That will bring back up the list of all known clients and you can add/remove tracked clients there.
- Tracking the AP info is exactly the direction I think we should go.  I'm hoping we can find a way to do all that under the device registry where the APs are created now.  If not, we can either create an entity and device per AP or create only an entity per AP.
- It looks like HA will reformat None to a standard "-".  I haven't found what's best practice yet but I'll keep looking.

**Comment by apaperclip** [comment]
> Nice! Glad you got a good dev/test setup going.
> 
> * The polling interval was actually really easy to add.  I've got it working but need to figure out how to enforce the minimum.  Shouldn't be hard.

>> very cool, what's wrong with sub-second polling :)

> * My goal for tracking specific clients would be to use an options flow.  It would be automatically invoked after you first submit the info to add the component.  As soon as you click "submit" we'll validate that your info is good, from there you'll get a form with a list of all discovered clients.  You check the ones you want to track and we'll create entities for those.  After that first setup, you can click the "options" button on the integration for the component.  That will bring back up the list of all known clients and you can add/remove tracked clients there.

>> 👍  "all known" aka "all ever known", as an ever increasing list of clients that have ever associated?  I like it, but should this be prunable? Not that I'm doing wifi for a stadium or anything. Maybe set a max age lifetime if never 'enabled/tracked"?

> * Tracking the AP info is exactly the direction I think we should go.  I'm hoping we can find a way to do all that under the device registry where the APs are created now.  If not, we can either create an entity and device per AP or create only an entity per AP.

> * It looks like HA will reformat None to a standard "-".  I haven't found what's best practice yet but I'll keep looking.

I got an answer to the logo question on discord, the logo pr should be done before the code PR. I can try to get that done if you like. We may have to answer some bigger questions like "why dont you update the existing component instead", "what are your plans to decom the old one", etc

**Comment by mww012** [comment]
Awesome.  Thanks!  I don't think we'll have issues answering those kinds of questions.  There's a pretty good incentive to re-write vs updating the original component.

I made a decent bit of progress on the client tracking side of things a little earlier.  I'll push the updates to my fork as soon as it can actually do something without throwing up, lol.

**Comment by apaperclip** [comment]
logo pr here https://github.com/home-assistant/brands/pull/1792
